version: 2.1
commands:
  setup:
    parameters:
      # Docker image is different for each executors.
      # So use docker image provider name as prefix.
      prefix:
        type: string
        default: circleci
    steps:
      - checkout

      - restore_cache:
          keys:
            - << parameters.prefix >>-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - << parameters.prefix >>-yarn-packages-{{ .Branch }}
            - << parameters.prefix >>-yarn-packages-

      - run:
          command: |
            yarn config set cache-folder ~/.cache
            yarn install --frozen-lockfile

      - save_cache:
          paths:
            # Cache both yarn and cypress.
            - ~/.cache
          key: << parameters.prefix >>-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

executors:
  default-executor:
    docker:
      - image: circleci/node:12.13

  for-e2e-testing-executor:
    docker:
      # `12.13` was not registered.
      # https://hub.docker.com/r/cypress/base/tags
      - image: cypress/base:12.13.0
    environment:
      TERM: xterm

jobs:
  build-test-unit:
    executor: default-executor

    steps:
      - setup

      - run: yarn lint --no-fix

      - run: yarn test:unit

  build-test-e2e:
    executor: for-e2e-testing-executor

    steps:
      - setup:
          prefix: cypress

      - run: yarn test:e2e --headless

  deploy:
    executor: default-executor

    steps:
      - setup

      - add_ssh_keys:
          fingerprints:
            - "28:d8:8e:4b:61:c6:81:fc:6c:c7:a5:14:a1:f5:98:e2"

      - run:
          command: |
            yarn build
            yarn deploy -d dist -b master --silent -m "[ci skip] Automatic deployment from CircleCI" --user "tsukachu <concon.ch.1543@gmail.com>"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test-unit:
          filters:
            branches:
              ignore: master

      - build-test-e2e:
          filters:
            branches:
              ignore: master

      - hold:
          type: approval
          requires:
            - build-test-unit
            - build-test-e2e
          filters:
            branches:
              only: develop

      - deploy:
          requires:
            - hold
