version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock"}}
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run: yarn lint

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
